export const SIGNIN_PENDING = 'SIGNIN/PENDING';
export const SIGNIN_SUCCESS = 'SIGNIN/SUCCESS_SIGNIN';
export const SIGNIN_FATAL = 'SIGNIN/FATAL_SIGNIN';
export const SIGNIN_CLEAR_ERROR = 'SIGNIN/SIGNIN_CLEAR_ERROR';
