export const SIGNIN_PENDING = 'SIGNIN/PENDING';
export const SIGNIN_STOP_PENDING = 'SIGNIN/SIGNIN_STOP_PENDING';
export const SIGNIN_ERROR = 'SIGNIN/SIGNIN_ERROR';
export const SIGNIN_CLEAR_ERROR = 'SIGNIN/SIGNIN_CLEAR_ERROR';
