export const AUTHORIZE = 'AUTH/AUTHORIZE';
export const PENDING_AUTHORIZE_CHECK = 'AUTH/PENDING_AUTHORIZE_CHECK';
export const AUTHORIZE_CHECK_COMPLETED = 'AUTH/AUTHORIZE_CHECK_COMPLETED';
export const LOGOUT = 'AUTH/LOGOUT';
export const CHANGE_AVATAR = 'AUTH/CHANGE_AVATAR';
