export const LOAD_LEADERBOARD_REQUEST = 'LEADERS/LOAD_LEADERBOARD_REQUEST';
export const LOAD_LEADERBOARD_SUCCESS = 'LEADERS/LOAD_LEADERBOARD_SUCCESS';
export const LOAD_LEADERBOARD_ERROR = 'LEADERS/LOAD_LEADERBOARD_ERROR';
export const PUSH_LEADERS_LIST = 'LEADERS/PUSH_LEADERS_LIST';
