export const START_PENDING_LEADERS = 'LEADERS/START_PENDING_LEADERS';
export const STOP_PENDING_LEADERS = 'LEADERS/STOP_PENDING_LEADERS';
export const PUSH_LEADERS_LIST = 'LEADERS/PUSH_LEADERS_LIST';
export const SET_ERROR_MESSAGE = 'LEADERS/SET_ERROR_MESSAGE';
