export const AVATAR_PENDING = 'USER_SETTINGS/AVATAR_PENDING';
export const AVATAR_SUCCESS = 'USER_SETTINGS/AVATAR_SUCCESS';
export const AVATAR_FATAL = 'USER_SETTINGS/AVATAR_FATAL';
export const AVATAR_CLEAR_ERROR = 'USER_SETTINGS/AVATAR_CLEAR_ERROR';

export const CHANGE_PASSWORD_PENDING = 'USER_SETTINGS/CHANGE_PASSWORD_PENDING';
export const CHANGE_PASSWORD_SUCCESS = 'USER_SETTINGS/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FATAL = 'USER_SETTINGS/CHANGE_PASSWORD_FATAL';
export const CHANGE_PASSWORD_CLEAR_ERROR = 'USER_SETTINGS/CHANGE_PASSWORD_CLEAR_ERROR';
export const CHANGE_PASSWORD_IS_MISMATCH = 'USER_SETTINGS/PASSWORD_IS_MISMATCH';
