export const AVATAR_PENDING = 'USER_SETTINGS/AVATAR_PENDING';
export const AVATAR_STOP_PENDING = 'USER_SETTINGS/AVATAR_STOP_PENDING';
export const AVATAR_ERROR = 'USER_SETTINGS/AVATAR_ERROR';
export const AVATAR_CLEAR_ERROR = 'USER_SETTINGS/AVATAR_CLEAR_ERROR';

export const CHANGE_PASSWORD_PENDING = 'USER_SETTINGS/CHANGE_PASSWORD_PENDING';
export const CHANGE_PASSWORD_STOP_PENDING = 'USER_SETTINGS/CHANGE_PASSWORD_STOP_PENDING';
export const CHANGE_PASSWORD_ERROR = 'USER_SETTINGS/CHANGE_PASSWORD_ERROR';
export const CHANGE_PASSWORD_CLEAR_ERROR = 'USER_SETTINGS/CHANGE_PASSWORD_CLEAR_ERROR';
export const CHANGE_PASSWORD_IS_MATCHED = 'USER_SETTINGS/CHANGE_PASSWORD_IS_MATCHED';
