export const SIGNUP_PENDING = 'SIGNUP/SIGNUP_PENDING';
export const SIGNUP_SUCCESS = 'SIGNUP/SIGNUP_SUCCESS';
export const SIGNUP_FATAL = 'SIGNUP/SIGNUP_FATAL';
export const SIGNUP_CLEAR_ERROR = 'SIGNUP/SIGNUP_CLEAR_ERROR';
