export const SIGNUP_PENDING = 'SIGNUP/SIGNUP_PENDING';
export const SIGNUP_PENDING_STOP = 'SIGNUP/SIGNUP_PENDING_STOP';
export const SIGNUP_ERROR = 'SIGNUP/SIGNUP_ERROR';
export const SIGNUP_CLEAR_ERROR = 'SIGNUP/SIGNUP_CLEAR_ERROR';
